<?php
function client_family_init(){
  
    drupal_add_js('sites/all/modules/custom/client_family/client_family.js', array('scope'=>'footer'));
    if(arg(0) == 'user' && arg(2) == 'client_family' && arg(4) == 'detail') {
  //     $query = db_merge('cFamily')
  //     ->fields(array(
  //     'family_head' => arg(1),
  // ))
  // ->execute();
  // drupal_goto('user/'.arg(1).'/client_family/'.arg(3).'/detail');
     }
}

function client_family_menu(){
   
      $items['user/%/client_family/%/new'] = array(
        'title' => 'Family of Client',
        'page callback' => '_client_family_new',
        'access arguments' => array('access content'),
        'access callback' => 'user_is_logged_in',
        'type' => MENU_CALLBACK,
      );

      $items['user/%/client_family/detail'] = array(
        'title' => 'Family of Client',
        'page callback' => '_client_family',
        'access arguments' => array('access content'),
        'access callback' => 'user_is_logged_in',
        'type' => MENU_CALLBACK,
      );
      $items['user/%/client_family/%/delete'] = array(
        
        'title' => 'Family of Client',
        'page callback' => '_client_family_del',
        'access arguments' => array('access content'),
        'access callback' => 'user_is_logged_in',
        'type' => MENU_CALLBACK,
        
      );

      return $items;


}

function client_family_theme(){

return array(
  '_client_family' => array(
    'template' => 'client-family-page-template',
    'path' => drupal_get_path('module', 'client_family') . '/templates',
  ),
  '_client_family_new' => array(
    'template' => 'client-family-page-new',
    'path' => drupal_get_path('module', 'client_family') . '/templates',
  ),
);
}

function _client_family() {
return theme("_client_family");
}
function _client_family_new() {
return theme("_client_family_new");
}

function get_full_name($user_id) {
  $user_obj = user_load($user_id);
  $user_profile = profile2_load_by_user($user_obj, 'personal_information');
  $fullname = $user_profile->field_first_name['und'][0]['value'].($user_profile->field_middle_name['und'][0]['value'] ? ' '.$user_profile->field_middle_name['und'][0]['value'] : '').' '.$user_profile->field_last_name['und'][0]['value'];
  return $fullname;
}

// function client_spouse() {
//   $result = db_select('family_client', 'f')
//     ->fields('f', array('user_id'))
//     ->condition('fid', arg(3), '=')
//     ->condition('user_relation', '0', '=')
//     ->execute()->fetchAssoc();
//      return $result['user_id'];
// }


function client_relationship($relation) {
  if($relation == 1) {
    $relation = 'Child';
  }
  else if($relation == 2) {
    $relation = 'Grandchild';
  }
  else if($relation == 3) {
    $relation = 'Sibling';
  }
  else if($relation == 4) {
    $relation = 'Not Specified';
  }
  return $relation;
} 


function get_profile_link ($user_id, $current_client_name) {
  global $user;
  if(in_array('administrator', $user->roles) || in_array('admn', $user->roles) || in_array('paid_advisor', $user->roles)  ) {
    $user_path='advisor/'.arg(1).'/client';
    $profile_link = l($current_client_name, $user_path);
  }
  else {
    $profile_link = '';
  }
  return $profile_link;
}

function is_spouse_already_exist($user_id){
  $spouse_name = profile2_load_by_user(arg(1), 'personal_information')->field_spouse_first_name['und'][0]['value'].(profile2_load_by_user(arg(1), 'personal_information')->field_spouse_middle_name['und'][0]['value'] ? ' '.profile2_load_by_user(arg(1), 'personal_information')->field_spouse_middle_name['und'][0]['value'] : '').''.(profile2_load_by_user(arg(1), 'personal_information')->field_spouse_last_name['und'][0]['value'] ?  ' '.profile2_load_by_user(arg(1), 'personal_information')->field_spouse_last_name['und'][0]['value'] : '');
  return ($spouse_name);
}


function _client_beneficiaries_name($user_id){
  $user_data = user_load($user_id);
  $beneficiary_data = profile2_load_by_user($user_data, 'beneficiaries');
  $beneficiary_name = array();
  foreach ($beneficiary_data->field_beneficiaries['und'] as $key => $value) {
      $beneficiary_name[] = cleanOutput(field_collection_item_load($value['value'])->field_first_name['und'][0]['value'].(field_collection_item_load($value['value'])->field_middle_name['und'][0]['value'] ? ' '.field_collection_item_load($value['value'])->field_middle_name['und'][0]['value'] : '').' '.field_collection_item_load($value['value'])->field_last_name['und'][0]['value']);
    }
      return $beneficiary_name;
}

function _client_beneficiaries_status($user_id){
  $user_data = user_load($user_id);
  $beneficiary_data = profile2_load_by_user($user_data, 'beneficiaries');
  $beneficiary_status = array();
  foreach ($beneficiary_data->field_beneficiaries['und'] as $key => $value) {
      $beneficiary_status[] = cleanOutput(field_collection_item_load($value['value'])->field_beneficiary_relationship['und'][0]['value']);
    }
      return $beneficiary_status;
}


function _client_family_all_members() {
  $family_members = array();
  $result = db_select('family_client', 'f')
    ->fields('f', array('name', 'rid','user_relation'))
    ->condition('user_relation', '0', '<>')
    ->execute()->fetchAll();
  foreach ($result as $key => $value) {
    $family_members[$value->rid] = ['name' => $value-> name ,'relation'=> $value -> user_relation];
  }
  
  return $family_members;
}


function _client_family_form($form, $form_state) {
  $back = 'user/'.arg(1).'/client_family/'.arg(3).'/detail';

  $form['close'] = array(
    '#markup' => '<div id="create-form"><h3>Add a Family Member</h3></div>',
  );
  $form['name'] = array(
    '#title' => t('Name'),
    '#type' => 'textfield',
    '#attributes' => array('required' => 'required'),
    '#description' => t('Type name of family member'),
  );
  $family_head_spouse = is_spouse_already_exist(arg(1));

  if($family_head_spouse) {
    $select_options = ['1' => 'Child', '2' => 'Grandchild', '3' => 'Sibling', '4' => 'Not Specified'];
  }
  else {
    $select_options = ['0' => 'Spouse', '1' => 'Child', '2' => 'Grandchild', '3' => 'Sibling', '4' => 'Not Specified'];
  }
  $form['relation'] = array(
    '#title' => t('Relationship'),
    '#type' => 'select',
    '#options' => $select_options,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Add Family Member',
  );
  $form['cancel'] = array(
    '#type' => 'link',
    '#title' => 'Cancel',
    '#href' => $back
  );
  return $form;
}

function _client_family_form_submit($form, $form_state) {
     db_insert('family_client')
      ->fields(array(
      'fid' => arg(3),
      'name' => $form_state['values']['name'],
      'user_relation' => $form_state['values']['relation']
  ))
  ->execute();
  drupal_set_message('Member added successfully!');
}


function _client_family_delete_form($form, $form_state) {
  $form['close'] = array(
    '#markup' => '<h3>Are you sure you want to delete this family?</h3>',
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Delete',
  );
  $form['cancel'] = array(
    '#type' => 'link',
    '#href' => '#',
    '#title' => 'Cancel'
  );
  return $form;
}


function _client_family_delete_form_submit($form, $form_state) {
  $delete = db_delete('family_client')
    ->condition('fid', arg(3))
    ->execute();
  $delete = db_delete('cFamily')
    ->condition('fid', arg(1))
    ->execute();
  drupal_set_message('Family has been deleted succesfully!');
  drupal_goto('advisor/'.arg(1).'/client');
}
 
function get_id(){
 
 }
 

function _client_family_del_member_form($form, $form_state) {
  
  $form['close'] = array(
    '#markup' => '<h3>Delete this Family Member?</h3>',
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Remove',
  );
  $form['cancel'] = array(
    '#type' => 'link',
    '#href' => '#',
    '#title' => 'Cancel'
  );
  return $form;
}

function _client_family_del_member_form_submit($form, $form_state) {
  $member_id = $form_state['values']['member'];
    $member_delte = db_delete('family_client')
      ->condition('name', $member_id)
      ->execute();
    drupal_set_message('Member deleted successfully!');
  }


  function _client_family_del(){
   $content = array();
   $content[] = array('#markup'=> '<h2>helo</h2>');
   $content[] = drupal_get_form('_client_family_del_member_form');
   return $content;
  }